export const SUBMITLOGIN = 'SUBMITLOGIN';
export const LOGOUT = 'LOGOUT';
export const ERRORLOGIN = 'ERRORLOGIN';
export const LOADINGLOGIN = 'LOADINGLOGIN';

//Menu

export const ACTIVEMENU = 'ACTIVEMENU';
export const SUBMENUACTIVE = 'SUBMENUACTIVE';
export const ACTIVEREGISTERNEWUSER = 'ACTIVEREGISTERNEWUSER';
export const ACTIVEDELETEUSER = 'ACTIVEDELETEUSER';
export const ACTIVEERRORSPAM = 'ACTIVEERRORSPAM';
export const ACTIVEUPDATEUSER = 'ACTIVEUPDATEUSER';
export const ACTIVENEWEMPLEADO = 'ACTIVENEWEMPLEADO';
export const ACTIVESUBMENUEMPLEADOS = 'ACTIVESUBMENUEMPLEADOS';
export const ACTIVESUBMENUNEWCARGO = 'ACTIVESUBMENUNEWCARGO';
export const ACTIVESUBMENUUPDATECARGO = 'ACTIVESUBMENUUPDATECARGO';
export const ACTIVESUBMENUNEWROLE = 'ACTIVESUBMENUNEWROLE';
export const ACTIVESUBMENUUPDATEROLE = 'ACTIVESUBMENUUPDATEROLE';
export const ACTIVESUBMENUNUEWPUNTOVENTA = 'ACTIVESUBMENUNUEWPUNTOVENTA';
export const ACTIVESUBMENUUPDATEPUNTOVENTA = 'ACTIVESUBMENUUPDATEPUNTOVENTA';
export const ACTIVESUBMENUPUNTOVENTA = 'ACTIVESUBMENUPUNTOVENTA';
export const ACTIVESUBMENUNEWEMPLEADOR = 'ACTIVESUBMENUNEWEMPLEADOR';
export const ACTIVESUBMENUUPDATEEMPLEADOR = 'ACTIVESUBMENUUPDATEEMPLEADOR';
export const ACTIVESUBMENUUPDATEPASS = 'ACTIVESUBMENUUPDATEPASS';
export const ACTIVEDARKMODE = 'ACTIVEDARKMODE';
export const ACTIVEMENUVERACCESOS = 'ACTIVEMENUVERACCESOS';
export const ACTIVEMENUVERCONTRATO = 'ACTIVEMENUVERCONTRATO';
export const NEWNOTIFICACION = 'NEWNOTIFICACION';
export const LOADINGPUNTOVENTA = 'LOADINGPUNTOVENTA';
export const REMOTENOTIFICACION = 'REMOTENOTIFICACION';
export const STATECONEXIONSSE = 'STATECONEXIONSSE';